# Generated by Django 5.2.8 on 2025-11-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("serial_no", models.CharField(max_length=100)),
                ("previous_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64)),
            ],
        ),
    ]
