# Generated by Django 5.2.4 on 2025-11-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_trackinglog"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="meta_data_path",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="trackinglog",
            name="alert_message",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="trackinglog",
            name="is_suspicious",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="trackinglog",
            name="status",
            field=models.CharField(max_length=100),
        ),
    ]
