# Generated by Django 5.2.4 on 2025-11-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_block_meta_data_path_trackinglog_alert_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="denomination",
            field=models.CharField(default="Unknown", max_length=10),
        ),
    ]
