# Generated by Django 5.2.4 on 2025-12-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_block_denomination"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute_name", models.CharField(max_length=200)),
                ("license_id", models.CharField(max_length=100, unique=True)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("is_authorized", models.BooleanField(default=True)),
            ],
        ),
    ]
